### ISSUE TITLE
TS18003 : No inputs were found in config file tsconfig.json,

### ISSUE THREAD

**Issue by julienkermarec** [coturiv/ionic-electron-starter#1]
Hello,

i have this error when i build, i have tried to update typescript and change de tsconfig.json file, but it doesnt work.

`➜  ionic-electron-starter git:(master) ✗ npm run ele:build

> ionic-electron-starter@1.0.1 ele:build /Users/***/Electron/ionic-electron-starter
> tsc -p desktop

error TS18003: No inputs were found in config file '/Users/***/Electron/ionic-electron-starter/desktop/tsconfig.json'. Specified 'include' paths were '["src/**/*"]' and 'exclude' paths were '["./app"]'.

Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ionic-electron-starter@1.0.1 ele:build: `tsc -p desktop`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ionic-electron-starter@1.0.1 ele:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/***/.npm/_logs/2020-02-20T15_42_41_087Z-debug.log`

**Comment by coturiv** [comment]
Thanks for the issue, I've rewrote(just import from @capacitor/electron project) the electron side using Javascript, not Typescript. So you don't need transpiling, please ignore it and use `npm run build`.

See [here](https://github.com/coturiv/ionic-electron-starter/actions/runs/42323441/workflow#L54)

**Comment by julienkermarec** [comment]
Thank you for the response. Can you help me to add ipcRenderer with import ? I have searched 3 hours, but no success.

**Comment by coturiv** [comment]
https://github.com/coturiv/ionic-electron-starter/blob/master/src/app/shared/electron-ref.ts#L28

**Comment by julienkermarec** [comment]
Thank you very much ! Amazing support 😃
